#!/usr/bin/perl

print "Would you like to play a game?";
chomp($_ = <STDIN>);
if (/yes/i) {
	print "In that case, I recommend that you go bowling.\n";
}

$_ = "I saw Barney\ndown at the bowling alley\nwith Fred\nlast night.\n";
if (/Barney.*Fred/s) {
	print "That string mentions Fred after Barney!\n";
}

my $some_other = "I dream of betty rubble.";
if ($some_other =~ /\brub/) {
	print "Aye, there's the rub.\n";
}

print "Do you like Perl? ";
my $likes_perl = (<STDIN> =~ /\byes\b/i);
if ($likes_perl) {
	print "You said earlier that you like Perl, so...\n";
}
