#!/usr/bin/perl

use CGI qw(:all);

print header(),
	start_html("This is the page title"),
	h1( "Input parameters" );
print "\n";
my $list_items = "abc def ghi jkl";
foreach my $param ( param() ) {
	$list_items .= li( "$param: " . param($param) );
}

print ul( $list_items );
print end_html();
