#!/usr/bin/perl

# chdir '/etc' or die "cannot chdir to /etc: $!\n";
# chdir '/abc' or die "cannot chdir to /abc: $!\n";

foreach $arg (@ARGV) {
	print "one arg is $arg\n";
}

my @txt_files = glob '*.txt';
print "@txt_files\n";
my @txt_files_2 = <*.txt>;
print "@txt_files_2\n";

my $dir_to_process = '/etc';
opendir my $dh, $dir_to_process or die "Cannot open $dir_to_process: $!";
foreach $file (readdir $dh) {
	next unless $file =~ /\.conf$/;
	print "one file in $dir_to_process is $file\n";
}
closedir $dh;
