#!/usr/bin/perl

$fred = 3;
$barney = 4;
$wilma = &sum_of_fred_and_barney;
print "\$wilma is $wilma.\n";

$betty = 3 * &sum_of_fred_and_barney;
print "\$betty is $betty.\n";

print &max(10,34);
print "\n";

sub sum_of_fred_and_barney {
	print "Hey, you called the sum_of_fred_and_barney subroutine!\n";
	$fred + $barney; 
}

sub max {
	# Compare this to &larget_of_fred_or_barney
	if ($_[0] > $_[1]) {
		$_[0];
	} else {
		$_[1];
	}
}
